USE People

ALTER TABLE Users
DROP CONSTRAINT PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_Users
PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT UQ_Username_Users
UNIQUE (Username)

ALTER TABLE Users
ADD CONSTRAINT CK_UsernameAtLeastThreeSymbols_Users
CHECK (LEN(Username) >= 3)